### ISSUE TITLE
Problème sur le webservice

### ISSUE THREAD

**Issue by R-Alexandre** [naegi/Mandelbrot#1]
Quand je lance flask et que j'ouvre la page web, dans la console j'ai une erreur qui apparait sur la ligne 
``filename = Path(f"{zoom}/{x}/{y}.png")``
du main. Il dit que la syntaxe est mauvaise ... j'ai tenté plusieurs fix mais ça se transforme en un souci pour trouver les fichiers : il dit qu'il ne les trouve pas

**Comment by naegi** [comment]
Tu as quelle version de python ?

**Comment by R-Alexandre** [comment]
Python : 3.4.1, Flask : 0.12.2

**Comment by naegi** [comment]
Ok, python 3.4 ne supporte pas les f-strings (c'est arrivé en 3.6 je crois)
Tu peux simplement remplacer la ligne par:
```
filename = Path("{}/{}/{}.png".format(zoom, x, y))
```

**Comment by R-Alexandre** [comment]
Hum, tout n'est pas résolu, maintenant j'ai un souci sur la suite : 

FileNotFoundError: [Errno 2] No such file or directory: '/Users/Raphael/Desktop/Mandelbrot/webservice/cache'

J'imagine que c'est la ligne 27 qui coince

**Comment by naegi** [comment]
Bon... Encore un problème de compatibilité python 3.6
if faut remplacer 
`complete_filename.parent.mkdir(parents=True, exist_ok=True)`
par
```
import os
os.makedirs(str(complete_filename), exist_ok=True)
```
Je commit les corrections

**Comment by R-Alexandre** [comment]
Encore un souci .. :( Je comprends même pas le souci là



os.makedirs(str(complete_filename), exist_ok = True)
                                                       ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by naegi** [comment]
ça signifie que tu as utilisé une tabulation, alors que moi je programme avec des espaces ^^ 
Et python aime pas quand y a ça

**Comment by R-Alexandre** [comment]
Ah oui .... bravo les mecs qui ont fait cette particularité x)

**Comment by naegi** [comment]
C'est logique, une tabulation, ça peut valoir 2 espaces, 4 espaces ou 8 espaces... Donc c'est pas clair

**Comment by R-Alexandre** [comment]
Ceci dit j'ai toujours l'erreur suivante

FileNotFoundError: [Errno 2] No such file or directory: '/Users/Raphael/Desktop/Mandelbrot/webservice/cache'

**Comment by naegi** [comment]
Je récupère une version de python 3.4 et je teste

**Comment by naegi** [comment]
Tu peux réessayer ?

**Comment by R-Alexandre** [comment]
J'obtient : 

 File "/Users/Raphael/Desktop/Mandelbrot/webservice/main.py", line 44, in img
    subprocess.run(["../mandelbrot", str(zoom), str(x),
AttributeError: 'module' object has no attribute 'run'

**Comment by naegi** [comment]
J'ai pas réussi à avoir python 3.4 rapidement
Oh les problèmes de compatibilité, ça me saoule ! 
ill suffit de changer `run` en `call`

**Comment by naegi** [comment]
on est à la fin de la fonction, j'espère qu'il n'y aura pas d'autres soucis

**Comment by R-Alexandre** [comment]
Je crois que ça marche :-)

**Comment by naegi** [comment]
Ouff
